### ISSUE TITLE
docker: integrate flux-accounting with fluxorama interactive image

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#22]
Setting up an interactive Docker image with flux-accounting included in the `fluxorama` image would probably be a good testing environment for getting hands-on experience with the accounting tools. 

##### the interactive Dockerfile right now

Here are the contents of the Dockerfile as of now:

```
FROM grondo/fluxorama

LABEL maintainer="Christopher Moussa <moussa1@llnl.gov>"

COPY . /usr/lib64/flux-accounting/

RUN yum -y update \
  && yum install -y python3-pip python3-devel git \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --user --upgrade pip \
  && pip3 install tox

# go into flux-accounting, install dependencies, and run unit tests
RUN cd /usr/lib64/flux-accounting/ \
  && make dependencies \
  && make install \
  && make check \
  && pip3 install -r requirements.txt --user \
  && cd accounting/ \
  && ./create_db.py
```

This will place `flux-accounting` into `/usr/lib64/`.

##### install process 

Trying to run `flux account` after going into the image will result in the following error:

```
 [fluxuser@6c6b7e187062 flux-accounting]$ flux account -h
Traceback (most recent call last):
  File "/usr/libexec/flux/cmd/flux-account.py", line 11, in <module>
    load_entry_point('flux-accounting==0.1.0', 'console_scripts', 'flux-account.py')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/flux/python3.6/flux_accounting-0.1.0-py3.6.egg/accounting/accounting_cli.py", line 16, in <module>
ModuleNotFoundError: No module named 'pandas'
```

I can go into `flux-accounting` and install the dependencies with `pip3`:

```
$ [fluxuser@6c6b7e187062 flux-accounting]$ pip3 install -r requirements.txt --user
```

And now I can run the subcommands:

```
 [fluxuser@6c6b7e187062 flux-accounting]$ flux account -h
usage: flux-account.py [-h] {view-user,add-user,delete-user,edit-user} ...

Description: Translate command line arguments into SQLite instructions for the
Flux Accounting Database.

positional arguments:
  {view-user,add-user,delete-user,edit-user}
                        sub-command help
    view-user           view a user's information in the accounting database
    add-user            add a user to the accounting database
    delete-user         remove a user from the accounting database
    edit-user           edit a user's value
```

I can write to the database with `sudo`, which I think makes sense because `fluxuser` wouldn't necessarily be an admin and have permissions to add/remove users to **FluxAccounting.db**:

```
 [fluxuser@6c6b7e187062 accounting]$ sudo flux account add-user --username=fluxuser --admin-level=1 --account=acct --parent-acct=pacct --shares=10 --max-jobs=100 --max-wall-pj=1440
```

But I don't need `sudo` to view a user's account information (which, again, I think is appropriate behavior):

```
 [fluxuser@6c6b7e187062 accounting]$ flux account view-user fluxuser
   id_assoc  creation_time    mod_time  deleted user_name  admin_level account parent_acct  shares  max_jobs  max_wall_pj
0         1     1594237425  1594237425        0  fluxuser            1    acct       pacct      10       100         1440
```

I can think of a couple of things right now that my Dockerfile needs to be improved:

- the `--install-libs` option in my **Makefile** needed to be changed in order for `make install` to work. It needed to change from `/usr/lib/flux/python${FLUX_PYTHON_VERSION}/` to `/usr/lib64/flux/python${FLUX_PYTHON_VERSION}/`. I'm assuming this is due to the location of the Flux install in the Docker image?

- the dependencies for `flux-accounting` need to be linked in order for the subcommands to work. My hack was to run `pip3 install -r requirements.txt --user` again, but maybe there is another way to do this in the Dockerfile while the image is being built?

I'll continue to try and update this issue with changes made to the Dockerfile or the build process to get this properly set up.

**Comment by cmoussa1** [comment]
Okay, I think I was able to solve the `No module named 'pandas'` error by installing the dependencies to `/usr/local/lib64/python3.6/site-packages/` instead of `--user`, which I think was installing them to `root/.local/`.

**Comment by cmoussa1** [comment]
Here is the final `Dockerfile` that I sent out to the stakeholders to interact with:

```
FROM grondo/fluxorama:latest

LABEL maintainer="Christopher Moussa <moussa1@llnl.gov>"

COPY . /usr/lib64/flux-accounting/

RUN yum -y update \
  && yum install -y python3-pip python3-devel git \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --user --upgrade pip \
  && pip3 install tox

# go into flux-accounting, install dependencies, and run unit tests
RUN cd /usr/lib64/flux-accounting/ \
  && pip3 install -r requirements.txt -t /usr/local/lib64/python3.6/site-packages/ \
  && make install \
  && make check

# load job-archive module
RUN printf "#!/bin/bash\nflux module load job-archive dbpath=/var/lib/flux/jobs.db\n" \
        >/etc/flux/rc1.d/job-archive \
  && chmod +x /etc/flux/rc1.d/job-archive

# make directory for flux-accounting database
RUN mkdir /var/lib/flux-ba

# create flux-accounting database where fluxuser is the "admin"
RUN cd /usr/lib64/flux-accounting/accounting/ \
  && ./create_db.py -p /var/lib/flux-ba/FluxAccounting.db \
  && chown -R fluxuser /var/lib/flux-ba/
```

---

```
# load job-archive module
RUN printf "#!/bin/bash\nflux module load job-archive dbpath=/var/lib/flux/jobs.db\n" \
        >/etc/flux/rc1.d/job-archive \
  && chmod +x /etc/flux/rc1.d/job-archive
```

This loads the `job-archive` module and create a database to store inactive jobs. When they are placed here, the database is preserved across restarts and can be accessed with SQLite queries. Flux will not launch successfully if the `job-archive` module is not executable. 

Inside of `/var/lib/`, a new directory gets created called `flux-ba` that will hold the flux-accounting database. This database is also preserved across restarts, and can _also_ be accessed with SQLite queries as well as with the `flux account` subcommands. 

I think the caveat for read/write access to the SQLite databases is the same permissions should also be reflected in the directory the database file is located in, i.e. the user must also have permissions to the directory the .db file is in [[1]](https://serverfault.com/questions/57596/why-do-i-get-sqlite-error-unable-to-open-database-file), so that's something I would need to look out for.

**Comment by cmoussa1** [comment]
I am going to close this issue since I have a working Dockerfile to create an interactive Docker container with `flux-accounting` and the job-archive DB installed.
