### ISSUE TITLE
flux account-update-db: ERROR:root:unable to open database file

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-accounting#285]
Problem:  `flux account-update-db` makes a temporary copy of the database in the current working directory, which may fail depending on the credentials the command is run with, and the working directory of the user.
```
garlick@picl0:~$ sudo -u flux flux account-update-db
ERROR:root:unable to open database file
```
This snippet of strace demonstrates what happened when I tried to run the command as the `flux` user from my home directory:
```
openat(AT_FDCWD, "/var/lib/flux/FluxAccounting.db", O_RDWR|O_NOFOLLOW|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=49152, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=49152, ...}) = 0
newfstatat(AT_FDCWD, "/var/lib/flux/FluxAccounting.db", {st_mode=S_IFREG|0644, st_size=49152, ...}, 0) = 0
pread64(3, "SQLite format 3\0\20\0\1\1\0@  \0\0\0\21\0\0\0\f"..., 100, 0) = 100
mkdirat(AT_FDCWD, ".", 0777)            = -1 EEXIST (File exists)
newfstatat(AT_FDCWD, ".", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "tmpFluxAccounting.db", 0x7fd7f524e8, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
getcwd("/nfshome/garlick", 511)         = 17
getpid()                                = 103233
newfstatat(AT_FDCWD, "/nfshome/garlick/tmpFluxAccounting.db", 0x7fd7f520d8, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nfshome/garlick/tmpFluxAccounting.db", O_RDWR|O_CREAT|O_NOFOLLOW|O_CLOEXEC, 0644) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "/nfshome/garlick/tmpFluxAccounting.db", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
getpid()                                = 103233
write(2, "ERROR:root:unable to open databa"..., 40ERROR:root:unable to open database file
) = 40
fstat(3, {st_mode=S_IFREG|0644, st_size=49152, ...}) = 0
newfstatat(AT_FDCWD, "/var/lib/flux/FluxAccounting.db", {st_mode=S_IFREG|0644, st_size=49152, ...}, 0) = 0
close(3)                             
```

**Comment by garlick** [comment]
A suggestion would be to create a unique temporary directory in /tmp for this.

This [class](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) may be helpful.  Since the database contains user data, the directory should be removed afterwards on all exit paths.

**Comment by garlick** [comment]
When we updated fluke to flux-accounting 0.20, the update script tried to run but failed with the above when running as the flux user.  Probably because it is running from flux cron in the broker's current working directory which is /:
```
[root@fluke1:flux]# ps -fu flux|grep broker
flux        2067       1  0 10:32 ?        00:00:55 broker --config-path=/etc/fl
[root@fluke1:flux]# ls -l /proc/2067/cwd
lrwxrwxrwx 1 flux flux 0 Oct  5 12:44 /proc/2067/cwd -> /
```

@grondo captured the cron error:
```
ate-fshare; /bin/flux account-priority-update"": "flux-accounting database out of date; please update DB with 'flux account-update-db' before running commands"
te-fshare; /bin/flux account-priority-update"": "ERROR:root:unable to open database file"
ate-fshare; /bin/flux account-priority-update"": "flux-accounting database out of date; updating DB with 'flux account-update-db' before sending infomation to plugin"
te-fshare; /bin/flux account-priority-update"": "Traceback (most recent call last):"
te-fshare; /bin/flux account-priority-update"": "  File "/usr/libexec/flux/cmd/flux-account-priority-update.py", line 139, in <module>"
te-fshare; /bin/flux account-priority-update"": "    main()"
te-fshare; /bin/flux account-priority-update"": "  File "/usr/libexec/flux/cmd/flux-account-priority-update.py", line 135, in main"
te-fshare; /bin/flux account-priority-update"": "    bulk_update(path)"
te-fshare; /bin/flux account-priority-update"": "  File "/usr/libexec/flux/cmd/flux-account-priority-update.py", line 68, in bulk_update"
te-fshare; /bin/flux account-priority-update"": "    conn = est_sqlite_conn(path)"
te-fshare; /bin/flux account-priority-update"": "  File "/usr/libexec/flux/cmd/flux-account-priority-update.py", line 59, in est_sqlite_conn"
te-fshare; /bin/flux account-priority-update"": "    subprocess.run(["flux", "account-update-db", "-p", path], check=True)"
te-fshare; /bin/flux account-priority-update"": "  File "/usr/lib64/python3.6/subprocess.py", line 438, in run"
te-fshare; /bin/flux account-priority-update"": "    output=stdout, stderr=stderr)"
te-fshare; /bin/flux account-priority-update"": "subprocess.CalledProcessError: Command '['flux', 'account-update-db', '-p', '/var/lib/flux/FluxAccounting.db']' returned non-zero exit status 1."
t-priority-update"": Failed: Exit 1
```
He was able to get jobs running again by running the update script manually.  But anyway it sounds like this needs a fix more urgently.

**Comment by cmoussa1** [comment]
I'm about to post a PR that hopefully fixes this issue using the Python module you referenced in an above comment. The module enables the creation of the temporary database inside `/tmp/` that's used to upgrade the old DB.
