### ISSUE TITLE
ERROR: test/test_job_archive_interface.py - missing test plan

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-accounting#370]
Problem: as noted [here](https://github.com/flux-framework/flux-accounting/pull/357#issuecomment-1679558346), one of the unit tests is failing for me:
```
Traceback (most recent call last):
  File "/nfshome/garlick/proj/flux-accounting/src/bindings/python/fluxacct/accounting/./test/test_job_archive_interface.py", line 20, in <module>
    from fluxacct.accounting import job_archive_interface as jobs
  File "/nfshome/garlick/proj/flux-accounting/src/bindings/python/fluxacct/accounting/job_archive_interface.py", line 18, in <module>
    from flux.resource import ResourceSet
ModuleNotFoundError: No module named 'flux'
ERROR: test/test_job_archive_interface.py - missing test plan
ERROR: test/test_job_archive_interface.py - exited with status 1
```
This is a debian bullseye system with flux-core installed as a system package.

**Comment by garlick** [comment]
One note: if I run `flux make check`, the tests work, so perhaps something environmental with the unit tests.

**Comment by cmoussa1** [comment]
I wonder if the flux-accounting Python bindings is doing something incorrectly with `import`ing the `flux` Python module? Sorry, I feel like I am no help here 😩 FWIW, I think the `Makefile.am` for flux-accounting is the same as flux-sched's fluxion `Makefile.am`:

```make
SUBDIRS = accounting

install-data-hook:
	$(AM_V_at)echo Linking python modules in non-standard location... && \
	  $(INSTALL) -d -m 0755 "$(DESTDIR)$(fluxpylinkdir)" && \
	  target=$(fluxpydir) && \
	  f=$${target##*/} && \
	  cd "$(DESTDIR)$(fluxpylinkdir)" && \
	  rm -f $$f && \
	  $(LN_S) $$target .

uninstall-local:
	$(AM_V_at)target=$(fluxpydir) && f=$${target##*/} && \
	  echo "Removing $(fluxpylinkdir)/$$f" && \
	  rm -rf $(fluxpylinkdir)/$$f
```

**Comment by garlick** [comment]
I was thinking maybe the python environment  for unit tests would be the right place to start looking:
```
AM_TESTS_ENVIRONMENT = \
        export PYTHONPATH="$(abs_top_srcdir)/src/bindings/python/:$(abs_top_srcdir)/t/pycotap:$(PYTHON_SITE_PKG):$$PYTHONPATH";\
        export PYTHON="${PYTHON}";
```
https://github.com/flux-framework/flux-accounting/blob/master/src/bindings/python/fluxacct/accounting/Makefile.am#L28

But that _looks_ ok to me.  I must be missing something.

**Comment by cmoussa1** [comment]
I've since moved the Python unit tests to the `t/` directory, and they now run alongside the sharness tests. Not sure if that might have fixed this `missing test plan` error
