### ISSUE TITLE
view_job_records(): function takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#54]
Was trying to use `view_job_records()` in the interactive Docker container via the command line and am running into the following issue:

```
$ flux account -p /var/lib/flux/jobs.db view-job-records 

Traceback (most recent call last):
  File "/usr/libexec/flux/cmd/flux-account.py", line 11, in <module>
    load_entry_point('flux-accounting==0.1.0', 'console_scripts', 'flux-account.py')()
  File "/usr/lib64/flux/python3.6/flux_accounting-0.1.0-py3.6.egg/accounting/accounting_cli.py", line 204, in main
TypeError: view_job_records() takes 2 positional arguments but 3 were given
```

The function definition for `view_job_records()` is as follows:

```python
def view_job_records(conn, output_file, **kwargs):
```

**Comment by cmoussa1** [comment]
Similar to the unit tests, I think this can be fixed by placing `args` in a dictionary and passing that to `view_job_records()`. 

```python
elif args.func == "view_job_records":
        opts = {
            'jobid': args.jobid,
            'user': args.user,
            'after_start_time': args.after_start_time,
            'before_end_time': args.before_end_time
        }
        aclif.view_job_records(conn, output_file, **opts)
```

```
flux account -p /var/lib/flux/jobs.db view-job-records -u fluxuser
   UserID  Username         JobID         T_Submit            T_Run       T_Inactive  Nodes                                                                            R
0    2001  fluxuser  658673500160 1602102753.80507 1602102753.82697 1602102753.90663      1  {"version":1,"execution":{"R_lite":[{"rank":"0","children":{"core":"0"}}]}}
1    2001  fluxuser  605808492544 1602102750.65387 1602102750.67244 1602102750.75700      1  {"version":1,"execution":{"R_lite":[{"rank":"0","children":{"core":"0"}}]}}
2    2001  fluxuser  549168611328 1602102747.27801 1602102747.30085 1602102747.38107      1  {"version":1,"execution":{"R_lite":[{"rank":"0","children":{"core":"0"}}]}}
3    2001  fluxuser  501689090048 1602102744.44805 1602102744.46866 1602102744.54671      1  {"version":1,"execution":{"R_lite":[{"rank":"0","children":{"core":"0"}}]}}
4    2001  fluxuser  464930209792 1602102742.25715 1602102742.28018 1602102742.36704      1  {"version":1,"execution":{"R_lite":[{"rank":"0","children":{"core":"0"}}]}}
```
