### ISSUE TITLE
flux account -h errors out

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-accounting#60]
I used the python virtual environment to create a local development environment (e.g., using python setup.py develop).

```console
(local_venv)  [fluxuser@7b0a61e07aa7 test]$ which flux-account.py
/usr/src/local_venv/bin/flux-account.py
```

And then I set up 
```
(local_venv)  [fluxuser@7b0a61e07aa7 test]$ export FLUX_EXEC_PATH_PREPEND=/usr/src/local_venv/bin
```

But `flux account` command encounters an error

```console
(local_venv)  [fluxuser@7b0a61e07aa7 test]$
(local_venv)  [fluxuser@7b0a61e07aa7 test]$
(local_venv)  [fluxuser@7b0a61e07aa7 test]$
(local_venv)  [fluxuser@7b0a61e07aa7 test]$ flux account -h
Traceback (most recent call last):
  File "/usr/src/local_venv/bin/flux-account.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flux-accounting' distribution was not found and is required by the application
```

**Comment by cmoussa1** [comment]
I think this issue was created before #73 was landed; now that flux-accounting's structure looks different, I'm not sure if this issue still persists?

**Comment by cmoussa1** [comment]
Talked offline with @SteVwonder about this and came to the conclusion that this is probably safe to close; I can always re-open if needed.
