### ISSUE TITLE
delete-user: subcommand needs to be updated to include 'bank' argument

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#95]
Trying to delete a user results in the following error:

```console
[fluxuser@30451d797d82 accounting-DB]$ flux account -p FluxAccounting.db delete-user user1
Traceback (most recent call last):
  File "/usr/libexec/flux/cmd/flux-account.py", line 249, in <module>
    main()
  File "/usr/libexec/flux/cmd/flux-account.py", line 220, in main
    aclif.delete_user(conn, args.username)
```

The `delete-user` subcommand needs to be updated to require a `bank` argument as well:

```python
subparser_delete_user = subparsers.add_parser(
    "delete-user", help="remove a user from the accounting database"
)
subparser_delete_user.set_defaults(func="delete_user")
subparser_delete_user.add_argument(
    "username", help="username", metavar=("USERNAME")
)
subparser_delete_user.set_defaults(func="delete_user")
subparser_delete_user.add_argument(
    "bank", help="bank", metavar=("BANK")
)
```

...

```python
elif args.func == "delete_user":
    aclif.delete_user(conn, args.username, args.bank)
```

**Comment by cmoussa1** [comment]
Ah, okay so I found a couple of issues with `delete-user` as a result of fixing this:

There was a foreign key constraint failure that occurs when you try to remove a user from the flux-accounting database:

```console
[fluxuser@52079229c00b accounting-DB]$ flux account -p FluxAccounting.db delete-user user1 B
Traceback (most recent call last):
  File "/usr/libexec/flux/cmd/flux-account.py", line 252, in <module>
    main()
  File "/usr/libexec/flux/cmd/flux-account.py", line 223, in main
    aclif.delete_user(conn, args.username, args.bank)
  File "/usr/lib64/flux/python3.6/flux/accounting/accounting_cli_functions.py", line 203, in delete_user
    cursor.execute(delete_stmt, (user, bank,))
sqlite3.IntegrityError: FOREIGN KEY constraint failed
``` 

This is because `user1`'s entry in the `job_usage_factor_table` references the `association_table` as a foreign key, so the entry becomes invalid, thus rejecting the `DELETE`.

The solution to avoiding this was to put an `ON DELETE CASCADE` option when creating the `job_usage_factor_table`, but we want to keep that history even when a user is deleted (removed in #92). What comes to mind is to remove the foreign key constraints on the `job_usage_factor_table` when creating the table; identical rows "should" be guaranteed since entries for both the `association_table` and the `job_usage_factor_table` happen at the same time when a user is added (see `add_user()`). 

---

The other problem was the absence of a `conn.commit()` in both `delete_user()` and `delete_bank()`. Without it, when you pass a subcommand to try and delete either a user or bank, the command succeeds, but doesn't keep the change. So I think I will need to add `conn.commit()` to both functions; one to `delete_user()` and one at the end of `delete_bank()`.
